// AI answer state — shown when the query reads like a question (isAskAIIntent).
//
// The answer itself is produced by the app's existing AI engine, injected as
// ctx.ai.buildMessage(q) -> { body, followups, intent }. `body` is ready-to-use
// HTML (with inline onclick navigation that the modal's hashchange handler turns
// into "navigate + close"). Follow-ups are rendered as in-modal buttons so they
// refine the answer without leaving the modal.

import { escapeHtml, escapeAttr } from '../lib/dom.js';

export function aiView(ctx, q) {
  const { body, followups } = ctx.ai.buildMessage(q);

  return `
    <div class="sm-ai">
      <div class="sm-ai-head"><span class="sm-ai-spark">✦</span> Manning AI · answering “${escapeHtml(q)}”</div>
      <div class="sm-ai-body">${body}</div>
      <p class="sm-ai-note">Mock response — in production this would be generated by an LLM using the Manning catalog as context.</p>
      ${followups.length ? `
      <div class="sm-ai-followups">
        <div class="lbl">Suggested questions</div>
        ${followups.map((f) => `
          <button class="sm-ai-fq" data-sm-ai-followup="${escapeAttr(f)}">
            <span>${escapeHtml(f)}</span><span class="ar">→</span>
          </button>`).join('')}
      </div>` : ''}
    </div>
    <form class="sm-ai-composer" data-sm-ai-composer>
      <input type="text" placeholder="Ask a follow-up…" autocomplete="off" />
      <button type="submit" class="sm-ai-send" title="Send" aria-label="Send">↑</button>
    </form>`;
}
